/**
 * Global country reference list — ISO 3166-1 alpha-2 code, common name, a
 * default/primary language (ISO 639-1) where there's a reasonably clear
 * single answer, and a region grouping. Seeds CountryCoverage so every
 * workspace starts with a NOT_STARTED row per country rather than only
 * getting rows for countries a query happens to target.
 *
 * `defaultLanguage` is intentionally null for multilingual countries with no
 * single dominant language (e.g. Switzerland, India, Belgium) rather than
 * guessing — "if available" per the country list this seeds.
 */
export type CountrySeed = {
  code: string;
  name: string;
  defaultLanguage: string | null;
  region: string;
};

export const COUNTRIES: CountrySeed[] = [
  // Africa
  { code: "DZ", name: "Algeria", defaultLanguage: "ar", region: "Africa" },
  { code: "AO", name: "Angola", defaultLanguage: "pt", region: "Africa" },
  { code: "BJ", name: "Benin", defaultLanguage: "fr", region: "Africa" },
  { code: "BW", name: "Botswana", defaultLanguage: "en", region: "Africa" },
  { code: "BF", name: "Burkina Faso", defaultLanguage: "fr", region: "Africa" },
  { code: "BI", name: "Burundi", defaultLanguage: "fr", region: "Africa" },
  { code: "CM", name: "Cameroon", defaultLanguage: "fr", region: "Africa" },
  { code: "CV", name: "Cabo Verde", defaultLanguage: "pt", region: "Africa" },
  { code: "CF", name: "Central African Republic", defaultLanguage: "fr", region: "Africa" },
  { code: "TD", name: "Chad", defaultLanguage: "fr", region: "Africa" },
  { code: "KM", name: "Comoros", defaultLanguage: "ar", region: "Africa" },
  { code: "CG", name: "Congo", defaultLanguage: "fr", region: "Africa" },
  { code: "CD", name: "DR Congo", defaultLanguage: "fr", region: "Africa" },
  { code: "CI", name: "Côte d'Ivoire", defaultLanguage: "fr", region: "Africa" },
  { code: "DJ", name: "Djibouti", defaultLanguage: "fr", region: "Africa" },
  { code: "EG", name: "Egypt", defaultLanguage: "ar", region: "Africa" },
  { code: "GQ", name: "Equatorial Guinea", defaultLanguage: "es", region: "Africa" },
  { code: "ER", name: "Eritrea", defaultLanguage: null, region: "Africa" },
  { code: "SZ", name: "Eswatini", defaultLanguage: "en", region: "Africa" },
  { code: "ET", name: "Ethiopia", defaultLanguage: "am", region: "Africa" },
  { code: "GA", name: "Gabon", defaultLanguage: "fr", region: "Africa" },
  { code: "GM", name: "Gambia", defaultLanguage: "en", region: "Africa" },
  { code: "GH", name: "Ghana", defaultLanguage: "en", region: "Africa" },
  { code: "GN", name: "Guinea", defaultLanguage: "fr", region: "Africa" },
  { code: "GW", name: "Guinea-Bissau", defaultLanguage: "pt", region: "Africa" },
  { code: "KE", name: "Kenya", defaultLanguage: "en", region: "Africa" },
  { code: "LS", name: "Lesotho", defaultLanguage: "en", region: "Africa" },
  { code: "LR", name: "Liberia", defaultLanguage: "en", region: "Africa" },
  { code: "LY", name: "Libya", defaultLanguage: "ar", region: "Africa" },
  { code: "MG", name: "Madagascar", defaultLanguage: "fr", region: "Africa" },
  { code: "MW", name: "Malawi", defaultLanguage: "en", region: "Africa" },
  { code: "ML", name: "Mali", defaultLanguage: "fr", region: "Africa" },
  { code: "MR", name: "Mauritania", defaultLanguage: "ar", region: "Africa" },
  { code: "MU", name: "Mauritius", defaultLanguage: "en", region: "Africa" },
  { code: "MA", name: "Morocco", defaultLanguage: "ar", region: "Africa" },
  { code: "MZ", name: "Mozambique", defaultLanguage: "pt", region: "Africa" },
  { code: "NA", name: "Namibia", defaultLanguage: "en", region: "Africa" },
  { code: "NE", name: "Niger", defaultLanguage: "fr", region: "Africa" },
  { code: "NG", name: "Nigeria", defaultLanguage: "en", region: "Africa" },
  { code: "RW", name: "Rwanda", defaultLanguage: "rw", region: "Africa" },
  { code: "ST", name: "São Tomé and Príncipe", defaultLanguage: "pt", region: "Africa" },
  { code: "SN", name: "Senegal", defaultLanguage: "fr", region: "Africa" },
  { code: "SC", name: "Seychelles", defaultLanguage: "en", region: "Africa" },
  { code: "SL", name: "Sierra Leone", defaultLanguage: "en", region: "Africa" },
  { code: "SO", name: "Somalia", defaultLanguage: "so", region: "Africa" },
  { code: "ZA", name: "South Africa", defaultLanguage: "en", region: "Africa" },
  { code: "SS", name: "South Sudan", defaultLanguage: "en", region: "Africa" },
  { code: "SD", name: "Sudan", defaultLanguage: "ar", region: "Africa" },
  { code: "TZ", name: "Tanzania", defaultLanguage: "sw", region: "Africa" },
  { code: "TG", name: "Togo", defaultLanguage: "fr", region: "Africa" },
  { code: "TN", name: "Tunisia", defaultLanguage: "ar", region: "Africa" },
  { code: "UG", name: "Uganda", defaultLanguage: "en", region: "Africa" },
  { code: "ZM", name: "Zambia", defaultLanguage: "en", region: "Africa" },
  { code: "ZW", name: "Zimbabwe", defaultLanguage: "en", region: "Africa" },

  // Middle East
  { code: "BH", name: "Bahrain", defaultLanguage: "ar", region: "Middle East" },
  { code: "IR", name: "Iran", defaultLanguage: "fa", region: "Middle East" },
  { code: "IQ", name: "Iraq", defaultLanguage: "ar", region: "Middle East" },
  { code: "IL", name: "Israel", defaultLanguage: "he", region: "Middle East" },
  { code: "JO", name: "Jordan", defaultLanguage: "ar", region: "Middle East" },
  { code: "KW", name: "Kuwait", defaultLanguage: "ar", region: "Middle East" },
  { code: "LB", name: "Lebanon", defaultLanguage: "ar", region: "Middle East" },
  { code: "OM", name: "Oman", defaultLanguage: "ar", region: "Middle East" },
  { code: "PS", name: "Palestine", defaultLanguage: "ar", region: "Middle East" },
  { code: "QA", name: "Qatar", defaultLanguage: "ar", region: "Middle East" },
  { code: "SA", name: "Saudi Arabia", defaultLanguage: "ar", region: "Middle East" },
  { code: "SY", name: "Syria", defaultLanguage: "ar", region: "Middle East" },
  { code: "TR", name: "Turkey", defaultLanguage: "tr", region: "Middle East" },
  { code: "AE", name: "United Arab Emirates", defaultLanguage: "ar", region: "Middle East" },
  { code: "YE", name: "Yemen", defaultLanguage: "ar", region: "Middle East" },

  // Asia
  { code: "AF", name: "Afghanistan", defaultLanguage: "ps", region: "Asia" },
  { code: "AM", name: "Armenia", defaultLanguage: "hy", region: "Asia" },
  { code: "AZ", name: "Azerbaijan", defaultLanguage: "az", region: "Asia" },
  { code: "BD", name: "Bangladesh", defaultLanguage: "bn", region: "Asia" },
  { code: "BT", name: "Bhutan", defaultLanguage: "dz", region: "Asia" },
  { code: "BN", name: "Brunei", defaultLanguage: "ms", region: "Asia" },
  { code: "KH", name: "Cambodia", defaultLanguage: "km", region: "Asia" },
  { code: "CN", name: "China", defaultLanguage: "zh", region: "Asia" },
  { code: "GE", name: "Georgia", defaultLanguage: "ka", region: "Asia" },
  { code: "HK", name: "Hong Kong", defaultLanguage: "zh", region: "Asia" },
  { code: "IN", name: "India", defaultLanguage: null, region: "Asia" },
  { code: "ID", name: "Indonesia", defaultLanguage: "id", region: "Asia" },
  { code: "JP", name: "Japan", defaultLanguage: "ja", region: "Asia" },
  { code: "KZ", name: "Kazakhstan", defaultLanguage: "kk", region: "Asia" },
  { code: "KG", name: "Kyrgyzstan", defaultLanguage: "ky", region: "Asia" },
  { code: "LA", name: "Laos", defaultLanguage: "lo", region: "Asia" },
  { code: "MO", name: "Macau", defaultLanguage: "zh", region: "Asia" },
  { code: "MY", name: "Malaysia", defaultLanguage: "ms", region: "Asia" },
  { code: "MV", name: "Maldives", defaultLanguage: "dv", region: "Asia" },
  { code: "MN", name: "Mongolia", defaultLanguage: "mn", region: "Asia" },
  { code: "MM", name: "Myanmar", defaultLanguage: "my", region: "Asia" },
  { code: "NP", name: "Nepal", defaultLanguage: "ne", region: "Asia" },
  { code: "KP", name: "North Korea", defaultLanguage: "ko", region: "Asia" },
  { code: "PK", name: "Pakistan", defaultLanguage: "ur", region: "Asia" },
  { code: "PH", name: "Philippines", defaultLanguage: "en", region: "Asia" },
  { code: "SG", name: "Singapore", defaultLanguage: "en", region: "Asia" },
  { code: "KR", name: "South Korea", defaultLanguage: "ko", region: "Asia" },
  { code: "LK", name: "Sri Lanka", defaultLanguage: "si", region: "Asia" },
  { code: "TW", name: "Taiwan", defaultLanguage: "zh", region: "Asia" },
  { code: "TJ", name: "Tajikistan", defaultLanguage: "tg", region: "Asia" },
  { code: "TH", name: "Thailand", defaultLanguage: "th", region: "Asia" },
  { code: "TL", name: "Timor-Leste", defaultLanguage: "pt", region: "Asia" },
  { code: "TM", name: "Turkmenistan", defaultLanguage: "tk", region: "Asia" },
  { code: "UZ", name: "Uzbekistan", defaultLanguage: "uz", region: "Asia" },
  { code: "VN", name: "Vietnam", defaultLanguage: "vi", region: "Asia" },

  // Europe
  { code: "AL", name: "Albania", defaultLanguage: "sq", region: "Europe" },
  { code: "AD", name: "Andorra", defaultLanguage: "ca", region: "Europe" },
  { code: "AT", name: "Austria", defaultLanguage: "de", region: "Europe" },
  { code: "BY", name: "Belarus", defaultLanguage: "be", region: "Europe" },
  { code: "BE", name: "Belgium", defaultLanguage: null, region: "Europe" },
  { code: "BA", name: "Bosnia and Herzegovina", defaultLanguage: "bs", region: "Europe" },
  { code: "BG", name: "Bulgaria", defaultLanguage: "bg", region: "Europe" },
  { code: "HR", name: "Croatia", defaultLanguage: "hr", region: "Europe" },
  { code: "CY", name: "Cyprus", defaultLanguage: "el", region: "Europe" },
  { code: "CZ", name: "Czechia", defaultLanguage: "cs", region: "Europe" },
  { code: "DK", name: "Denmark", defaultLanguage: "da", region: "Europe" },
  { code: "EE", name: "Estonia", defaultLanguage: "et", region: "Europe" },
  { code: "FI", name: "Finland", defaultLanguage: "fi", region: "Europe" },
  { code: "FR", name: "France", defaultLanguage: "fr", region: "Europe" },
  { code: "DE", name: "Germany", defaultLanguage: "de", region: "Europe" },
  { code: "GR", name: "Greece", defaultLanguage: "el", region: "Europe" },
  { code: "HU", name: "Hungary", defaultLanguage: "hu", region: "Europe" },
  { code: "IS", name: "Iceland", defaultLanguage: "is", region: "Europe" },
  { code: "IE", name: "Ireland", defaultLanguage: "en", region: "Europe" },
  { code: "IT", name: "Italy", defaultLanguage: "it", region: "Europe" },
  { code: "XK", name: "Kosovo", defaultLanguage: "sq", region: "Europe" },
  { code: "LV", name: "Latvia", defaultLanguage: "lv", region: "Europe" },
  { code: "LI", name: "Liechtenstein", defaultLanguage: "de", region: "Europe" },
  { code: "LT", name: "Lithuania", defaultLanguage: "lt", region: "Europe" },
  { code: "LU", name: "Luxembourg", defaultLanguage: "fr", region: "Europe" },
  { code: "MT", name: "Malta", defaultLanguage: "mt", region: "Europe" },
  { code: "MD", name: "Moldova", defaultLanguage: "ro", region: "Europe" },
  { code: "MC", name: "Monaco", defaultLanguage: "fr", region: "Europe" },
  { code: "ME", name: "Montenegro", defaultLanguage: "sr", region: "Europe" },
  { code: "NL", name: "Netherlands", defaultLanguage: "nl", region: "Europe" },
  { code: "MK", name: "North Macedonia", defaultLanguage: "mk", region: "Europe" },
  { code: "NO", name: "Norway", defaultLanguage: "no", region: "Europe" },
  { code: "PL", name: "Poland", defaultLanguage: "pl", region: "Europe" },
  { code: "PT", name: "Portugal", defaultLanguage: "pt", region: "Europe" },
  { code: "RO", name: "Romania", defaultLanguage: "ro", region: "Europe" },
  { code: "RU", name: "Russia", defaultLanguage: "ru", region: "Europe" },
  { code: "SM", name: "San Marino", defaultLanguage: "it", region: "Europe" },
  { code: "RS", name: "Serbia", defaultLanguage: "sr", region: "Europe" },
  { code: "SK", name: "Slovakia", defaultLanguage: "sk", region: "Europe" },
  { code: "SI", name: "Slovenia", defaultLanguage: "sl", region: "Europe" },
  { code: "ES", name: "Spain", defaultLanguage: "es", region: "Europe" },
  { code: "SE", name: "Sweden", defaultLanguage: "sv", region: "Europe" },
  { code: "CH", name: "Switzerland", defaultLanguage: null, region: "Europe" },
  { code: "UA", name: "Ukraine", defaultLanguage: "uk", region: "Europe" },
  { code: "GB", name: "United Kingdom", defaultLanguage: "en", region: "Europe" },
  { code: "VA", name: "Vatican City", defaultLanguage: "it", region: "Europe" },

  // North America
  { code: "AG", name: "Antigua and Barbuda", defaultLanguage: "en", region: "North America" },
  { code: "BS", name: "Bahamas", defaultLanguage: "en", region: "North America" },
  { code: "BB", name: "Barbados", defaultLanguage: "en", region: "North America" },
  { code: "BZ", name: "Belize", defaultLanguage: "en", region: "North America" },
  { code: "CA", name: "Canada", defaultLanguage: null, region: "North America" },
  { code: "CR", name: "Costa Rica", defaultLanguage: "es", region: "North America" },
  { code: "CU", name: "Cuba", defaultLanguage: "es", region: "North America" },
  { code: "DM", name: "Dominica", defaultLanguage: "en", region: "North America" },
  { code: "DO", name: "Dominican Republic", defaultLanguage: "es", region: "North America" },
  { code: "SV", name: "El Salvador", defaultLanguage: "es", region: "North America" },
  { code: "GD", name: "Grenada", defaultLanguage: "en", region: "North America" },
  { code: "GT", name: "Guatemala", defaultLanguage: "es", region: "North America" },
  { code: "HT", name: "Haiti", defaultLanguage: "fr", region: "North America" },
  { code: "HN", name: "Honduras", defaultLanguage: "es", region: "North America" },
  { code: "JM", name: "Jamaica", defaultLanguage: "en", region: "North America" },
  { code: "MX", name: "Mexico", defaultLanguage: "es", region: "North America" },
  { code: "NI", name: "Nicaragua", defaultLanguage: "es", region: "North America" },
  { code: "PA", name: "Panama", defaultLanguage: "es", region: "North America" },
  { code: "KN", name: "Saint Kitts and Nevis", defaultLanguage: "en", region: "North America" },
  { code: "LC", name: "Saint Lucia", defaultLanguage: "en", region: "North America" },
  { code: "VC", name: "Saint Vincent and the Grenadines", defaultLanguage: "en", region: "North America" },
  { code: "TT", name: "Trinidad and Tobago", defaultLanguage: "en", region: "North America" },
  { code: "US", name: "United States", defaultLanguage: "en", region: "North America" },

  // South America
  { code: "AR", name: "Argentina", defaultLanguage: "es", region: "South America" },
  { code: "BO", name: "Bolivia", defaultLanguage: "es", region: "South America" },
  { code: "BR", name: "Brazil", defaultLanguage: "pt", region: "South America" },
  { code: "CL", name: "Chile", defaultLanguage: "es", region: "South America" },
  { code: "CO", name: "Colombia", defaultLanguage: "es", region: "South America" },
  { code: "EC", name: "Ecuador", defaultLanguage: "es", region: "South America" },
  { code: "GY", name: "Guyana", defaultLanguage: "en", region: "South America" },
  { code: "PY", name: "Paraguay", defaultLanguage: "es", region: "South America" },
  { code: "PE", name: "Peru", defaultLanguage: "es", region: "South America" },
  { code: "SR", name: "Suriname", defaultLanguage: "nl", region: "South America" },
  { code: "UY", name: "Uruguay", defaultLanguage: "es", region: "South America" },
  { code: "VE", name: "Venezuela", defaultLanguage: "es", region: "South America" },

  // Oceania
  { code: "AU", name: "Australia", defaultLanguage: "en", region: "Oceania" },
  { code: "FJ", name: "Fiji", defaultLanguage: "en", region: "Oceania" },
  { code: "KI", name: "Kiribati", defaultLanguage: "en", region: "Oceania" },
  { code: "MH", name: "Marshall Islands", defaultLanguage: "en", region: "Oceania" },
  { code: "FM", name: "Micronesia", defaultLanguage: "en", region: "Oceania" },
  { code: "NR", name: "Nauru", defaultLanguage: "en", region: "Oceania" },
  { code: "NZ", name: "New Zealand", defaultLanguage: "en", region: "Oceania" },
  { code: "PW", name: "Palau", defaultLanguage: "en", region: "Oceania" },
  { code: "PG", name: "Papua New Guinea", defaultLanguage: "en", region: "Oceania" },
  { code: "WS", name: "Samoa", defaultLanguage: "en", region: "Oceania" },
  { code: "SB", name: "Solomon Islands", defaultLanguage: "en", region: "Oceania" },
  { code: "TO", name: "Tonga", defaultLanguage: "en", region: "Oceania" },
  { code: "TV", name: "Tuvalu", defaultLanguage: "en", region: "Oceania" },
  { code: "VU", name: "Vanuatu", defaultLanguage: "en", region: "Oceania" },
];

/** Case-insensitive lookup by common name — Business Brain COUNTRY_SERVED facts store names ("United States"), not ISO codes. */
export function findCountryByName(name: string): CountrySeed | undefined {
  const key = name.trim().toLowerCase();
  return COUNTRIES.find((c) => c.name.toLowerCase() === key);
}

